name: AWS Landing Zone Cleanup

on:
  schedule:
    - cron: '0 0 * * *'     # Every day at midnight UTC
  workflow_dispatch:         # Manual trigger option

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1   # Change to your preferred region

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Cleanup Script
      run: python cleanup/cleanup.py
